version: '3.4'

services:
  bor:
    container_name: bor
    image: gilani1364/bor:vlatest
    #build: bor
    volumes:
        - /data/polygon/bor:/root/.ethereum
    ports:
        - "127.0.0.1:8145:8545" # RPC
        - "127.0.0.1:8146:8546" # WS
        - "30137:30137" # Peers (TCP)
        - "30137:30137/udp" # Peers (UDP)
    command:
        - bor
        - --cache=8192
        - --syncmode=full
        - --bor.heimdall=http://heimdall-rest-server:1317
