version: '3.4'

services:
  bor:
    container_name: bor
    image: gilani1364/bor:latest
#    build: /data/polygon-node/bor
    volumes:
        - /data/polygon/bor:/root/.ethereum
    ports:
        - "8545:8545" # RPC
        - "8546:8546" # WS
        - "30137:30137" # Peers (TCP)
        - "30137:30137/udp" # Peers (UDP)
    command:
        - bor
        - --cache=8192
        - --syncmode=full
        - --datadir=/root/.ethereum
        - --networkid=137
        - --bor.heimdall=http://heimdall-rest-server:1317
        - --bor.logs
        - --miner.gaslimit=200000000
        - --miner.gastarget=20000000
        - --http
        - --http.addr=0.0.0.0
        - --http.port=8545
        - --http.api=eth,net,web3,admin,debug,bor
        - --http.corsdomain=*
        - --http.vhosts=*
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.port=8546
        - --ws.api=eth,net,web3,admin,debug,bor
        - --ws.origins=*
        - --nousb
        - --bootnodes=enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303
networks:
  default:
    name: polygon
    external: true
